{ title: '"Repeal and go f*ck yourself." Our first episode!',
 description: 'Jon Favreau, Jon Lovett and Tommy Vietor launch Pod Save America with a discussion of Russia hacking, cabinet confirmations, saving Obamacare and Obama\'s final speech. Then they\'re joined by Tamika Mallory and Linda Sarsour to discuss the Women\'s March on Washington.',
 summary: 'Jon Favreau, Jon Lovett and Tommy Vietor launch Pod Save America with a discussion of Russia hacking, cabinet confirmations, saving Obamacare and Obama\'s final speech. Then they\'re joined by Tamika Mallory and Linda Sarsour to discuss the Women\'s March on Washington.',
 date: 2017-01-09T20:53:01.000Z,
 pubdate: 2017-01-09T20:53:01.000Z,
 pubDate: 2017-01-09T20:53:01.000Z,
 link: null,
 guid: 'gid://art19-episode-locator/V0/IcxH1-o0wDmnd5p93ELmC6arLL4m-Qa7MDdc_MXQFlo',
 author: 'Crooked Media',
 comments: null,
 origlink: null,
 image: { url: 'https://dfkfj8j276wwv.cloudfront.net/images/0d/28/33/81/0d283381-724c-4caa-abad-b470e950d72d/b81bc65ae9ed5e2c095d68d40fecf3735467132e22415ad4861dd89a2f6527a47f45269a9091f8e98b499f5abc6c0c5423daa6690324ee9a0b9572868319deb7.jpeg' },
 source: {},
 categories: [],
 enclosures:
  [ { url: 'http://rss.art19.com/episodes/e2f548cd-a7f0-4874-9756-8aeb254af5e2.mp3',
      type: 'audio/mpeg',
      length: '49412806' } ],
 'rss:@': {},
 'rss:title':
  { '@': {},
    '#': '"Repeal and go f*ck yourself." Our first episode!' },
 'rss:description':
  { '@': {},
    '#': 'Jon Favreau, Jon Lovett and Tommy Vietor launch Pod Save America with a discussion of Russia hacking, cabinet confirmations, saving Obamacare and Obama\'s final speech. Then they\'re joined by Tamika Mallory and Linda Sarsour to discuss the Women\'s March on Washington.' },
 'itunes:summary':
  { '@': {},
    '#': 'Jon Favreau, Jon Lovett and Tommy Vietor launch Pod Save America with a discussion of Russia hacking, cabinet confirmations, saving Obamacare and Obama\'s final speech. Then they\'re joined by Tamika Mallory and Linda Sarsour to discuss the Women\'s March on Washington.' },
 'rss:guid':
  { '@': { ispermalink: 'false' },
    '#': 'gid://art19-episode-locator/V0/IcxH1-o0wDmnd5p93ELmC6arLL4m-Qa7MDdc_MXQFlo' },
 'rss:pubdate': { '@': {}, '#': 'Mon, 09 Jan 2017 20:53:01 -0000' },
 'itunes:explicit': { '@': {}, '#': 'yes' },
 'itunes:image': { '@': { href: 'https://dfkfj8j276wwv.cloudfront.net/images/0d/28/33/81/0d283381-724c-4caa-abad-b470e950d72d/b81bc65ae9ed5e2c095d68d40fecf3735467132e22415ad4861dd89a2f6527a47f45269a9091f8e98b499f5abc6c0c5423daa6690324ee9a0b9572868319deb7.jpeg' } },
 'itunes:keywords':
  { '@': {},
    '#': 'russia,obama,jon favreau,president obama ,Presidential Election,Trump,Women\'s March on Washington,Obamacare,Linda Sarsour,cabinet nominees,liberal ,Tamika Mallory,russian hacking,Jon Favreau,Dan Pfeiffer,politics,donald trump,POTUS,conservative,Pod Save America,Donald Trump,President Trump,Tommy Vietor,Jon Lovett' },
 'itunes:duration': { '@': {}, '#': '00:51:28' },
 'rss:enclosure':
  { '@':
     { url: 'http://rss.art19.com/episodes/e2f548cd-a7f0-4874-9756-8aeb254af5e2.mp3',
       type: 'audio/mpeg',
       length: '49412806' } },
 meta:
  { '#ns': [ [Object], [Object], [Object], [Object], [Object] ],
    '@': [ [Object], [Object], [Object] ],
    '#xml': { version: '1.0', encoding: 'UTF-8' },
    '#type': 'rss',
    '#version': '2.0',
    title: 'Pod Save America',
    description: 'Four former aides to President Obama — Jon Favreau, Dan Pfeiffer, Jon Lovett, and Tommy Vietor — are joined by journalists, politicians, comedians, and activists for a freewheeling conversation about politics, the press and the challenges posed by the Trump presidency.',
    date: null,
    pubdate: null,
    pubDate: null,
    link: 'https://art19.com/shows/pod-save-america',
    xmlurl: 'http://feeds.feedburner.com/pod-save-america',
    xmlUrl: 'http://feeds.feedburner.com/pod-save-america',
    author: 'Crooked Media',
    language: 'en',
    favicon: null,
    copyright: '© 2017 Crooked Media. All Rights Reserved.',
    generator: null,
    cloud: { type: 'hub', href: 'http://pubsubhubbub.appspot.com/' },
    image:
     { url: 'https://dfkfj8j276wwv.cloudfront.net/images/0d/28/33/81/0d283381-724c-4caa-abad-b470e950d72d/b81bc65ae9ed5e2c095d68d40fecf3735467132e22415ad4861dd89a2f6527a47f45269a9091f8e98b499f5abc6c0c5423daa6690324ee9a0b9572868319deb7.jpeg',
       title: 'Pod Save America' },
    categories: [ 'News & Politics' ],
    'rss:@': {},
    'rss:title': { '@': {}, '#': 'Pod Save America' },
    'rss:description':
     { '@': {},
       '#': 'Four former aides to President Obama — Jon Favreau, Dan Pfeiffer, Jon Lovett, and Tommy Vietor — are joined by journalists, politicians, comedians, and activists for a freewheeling conversation about politics, the press and the challenges posed by the Trump presidency.' },
    'rss:managingeditor':
     { '@': {},
       '#': 'hey@getcrookedmedia.com (Crooked Media)',
       name: 'Crooked Media',
       email: 'hey@getcrookedmedia.com' },
    'rss:copyright': { '@': {}, '#': '© 2017 Crooked Media. All Rights Reserved.' },
    'rss:link': { '@': {}, '#': 'https://art19.com/shows/pod-save-america' },
    'itunes:owner': { '@': {}, 'itunes:name': [Object], 'itunes:email': [Object] },
    'itunes:author': { '@': {}, '#': 'Crooked Media' },
    'itunes:summary':
     { '@': {},
       '#': 'Four former aides to President Obama — Jon Favreau, Dan Pfeiffer, Jon Lovett, and Tommy Vietor — are joined by journalists, politicians, comedians, and activists for a freewheeling conversation about politics, the press and the challenges posed by the Trump presidency.' },
    'rss:language': { '@': {}, '#': 'en' },
    'itunes:explicit': { '@': {}, '#': 'yes' },
    'itunes:category': { '@': [Object] },
    'itunes:keywords':
     { '@': {},
       '#': 'Jon Favreau,POTUS,Donald Trump,politics,Tommy Vietor,Dan Pfeiffer,Jon Lovett,Pod Save America' },
    'itunes:image': { '@': [Object] },
    'rss:image': { '@': {}, url: [Object], link: [Object], title: [Object] },
    'atom10:link': [ [Object], [Object] ],
    'feedburner:info': { '@': [Object] },
    'feedburner:browserfriendly': { '@': {} } } }
{ title: 'Teaser Episode',
 description: 'Pod Save America launches Monday January 9th!',
 summary: 'Pod Save America launches Monday January 9th!',
 date: 2017-01-06T16:20:40.000Z,
 pubdate: 2017-01-06T16:20:40.000Z,
 pubDate: 2017-01-06T16:20:40.000Z,
 link: null,
 guid: 'gid://art19-episode-locator/V0/4U3ILe11Y_Yf2EBEHJy9sI71O7ta3woGsiAyU4B_EYY',
 author: 'Crooked Media',
 comments: null,
 origlink: null,
 image: { url: 'https://dfkfj8j276wwv.cloudfront.net/images/0d/28/33/81/0d283381-724c-4caa-abad-b470e950d72d/b81bc65ae9ed5e2c095d68d40fecf3735467132e22415ad4861dd89a2f6527a47f45269a9091f8e98b499f5abc6c0c5423daa6690324ee9a0b9572868319deb7.jpeg' },
 source: {},
 categories: [],
 enclosures:
  [ { url: 'http://rss.art19.com/episodes/d4339286-59a8-4144-9b4f-36174ea4e221.mp3',
      type: 'audio/mpeg',
      length: '764447' } ],
 'rss:@': {},
 'rss:title': { '@': {}, '#': 'Teaser Episode' },
 'rss:description':
  { '@': {},
    '#': 'Pod Save America launches Monday January 9th!' },
 'itunes:summary':
  { '@': {},
    '#': 'Pod Save America launches Monday January 9th!' },
 'rss:guid':
  { '@': { ispermalink: 'false' },
    '#': 'gid://art19-episode-locator/V0/4U3ILe11Y_Yf2EBEHJy9sI71O7ta3woGsiAyU4B_EYY' },
 'rss:pubdate': { '@': {}, '#': 'Fri, 06 Jan 2017 16:20:40 -0000' },
 'itunes:explicit': { '@': {}, '#': 'yes' },
 'itunes:image': { '@': { href: 'https://dfkfj8j276wwv.cloudfront.net/images/0d/28/33/81/0d283381-724c-4caa-abad-b470e950d72d/b81bc65ae9ed5e2c095d68d40fecf3735467132e22415ad4861dd89a2f6527a47f45269a9091f8e98b499f5abc6c0c5423daa6690324ee9a0b9572868319deb7.jpeg' } },
 'itunes:keywords':
  { '@': {},
    '#': 'Jon Favreau,Dan Pfeiffer,politics,POTUS,Pod Save America,Donald Trump,Tommy Vietor,Jon Lovett' },
 'itunes:duration': { '@': {}, '#': '00:00:47' },
 'rss:enclosure':
  { '@':
     { url: 'http://rss.art19.com/episodes/d4339286-59a8-4144-9b4f-36174ea4e221.mp3',
       type: 'audio/mpeg',
       length: '764447' } },
 meta:
  { '#ns': [ [Object], [Object], [Object], [Object], [Object] ],
    '@': [ [Object], [Object], [Object] ],
    '#xml': { version: '1.0', encoding: 'UTF-8' },
    '#type': 'rss',
    '#version': '2.0',
    title: 'Pod Save America',
    description: 'Four former aides to President Obama — Jon Favreau, Dan Pfeiffer, Jon Lovett, and Tommy Vietor — are joined by journalists, politicians, comedians, and activists for a freewheeling conversation about politics, the press and the challenges posed by the Trump presidency.',
    date: null,
    pubdate: null,
    pubDate: null,
    link: 'https://art19.com/shows/pod-save-america',
    xmlurl: 'http://feeds.feedburner.com/pod-save-america',
    xmlUrl: 'http://feeds.feedburner.com/pod-save-america',
    author: 'Crooked Media',
    language: 'en',
    favicon: null,
    copyright: '© 2017 Crooked Media. All Rights Reserved.',
    generator: null,
    cloud: { type: 'hub', href: 'http://pubsubhubbub.appspot.com/' },
    image:
     { url: 'https://dfkfj8j276wwv.cloudfront.net/images/0d/28/33/81/0d283381-724c-4caa-abad-b470e950d72d/b81bc65ae9ed5e2c095d68d40fecf3735467132e22415ad4861dd89a2f6527a47f45269a9091f8e98b499f5abc6c0c5423daa6690324ee9a0b9572868319deb7.jpeg',
       title: 'Pod Save America' },
    categories: [ 'News & Politics' ],
    'rss:@': {},
    'rss:title': { '@': {}, '#': 'Pod Save America' },
    'rss:description':
     { '@': {},
       '#': 'Four former aides to President Obama — Jon Favreau, Dan Pfeiffer, Jon Lovett, and Tommy Vietor — are joined by journalists, politicians, comedians, and activists for a freewheeling conversation about politics, the press and the challenges posed by the Trump presidency.' },
    'rss:managingeditor':
     { '@': {},
       '#': 'hey@getcrookedmedia.com (Crooked Media)',
       name: 'Crooked Media',
       email: 'hey@getcrookedmedia.com' },
    'rss:copyright': { '@': {}, '#': '© 2017 Crooked Media. All Rights Reserved.' },
    'rss:link': { '@': {}, '#': 'https://art19.com/shows/pod-save-america' },
    'itunes:owner': { '@': {}, 'itunes:name': [Object], 'itunes:email': [Object] },
    'itunes:author': { '@': {}, '#': 'Crooked Media' },
    'itunes:summary':
     { '@': {},
       '#': 'Four former aides to President Obama — Jon Favreau, Dan Pfeiffer, Jon Lovett, and Tommy Vietor — are joined by journalists, politicians, comedians, and activists for a freewheeling conversation about politics, the press and the challenges posed by the Trump presidency.' },
    'rss:language': { '@': {}, '#': 'en' },
    'itunes:explicit': { '@': {}, '#': 'yes' },
    'itunes:category': { '@': [Object] },
    'itunes:keywords':
     { '@': {},
       '#': 'Jon Favreau,POTUS,Donald Trump,politics,Tommy Vietor,Dan Pfeiffer,Jon Lovett,Pod Save America' },
    'itunes:image': { '@': [Object] },
    'rss:image': { '@': {}, url: [Object], link: [Object], title: [Object] },
    'atom10:link': [ [Object], [Object] ],
    'feedburner:info': { '@': [Object] },
    'feedburner:browserfriendly': { '@': {} } } }
